USE [KristinsKitchen];
GO

set identity_insert [UserProfile] on
insert into UserProfile (Id, FirstName, LastName, Email, Phone, Bio, FirebaseId, ImageLocation, IsActive) values (1, 'Inactive', 'User', 'xxx@xxx.com', '123-456-7890', 'abc', 'abcdefghijklmnopqrstuvwxyz12', null, 0);
insert into UserProfile (Id, FirstName, LastName, Email, Phone, Bio, FirebaseId, ImageLocation, IsActive) values (2, 'David', 'Larsen', 'test@test.com', '547-926-4024', 'I am the very model of a modern Major-General. I''ve information vegetable, animal, and mineral. I know the kings of England, and I quote the fights historical, from Marathon to Waterloo, in order categorical. I''m very well acquainted too with matters mathematical. I understand equations, both the simple and quadratical. About binomial theorem I''m teeming with a lot o'' news with many cheerful facts about the square of the hypotenuse', 'mLyDPaYviJQiNc2dzxHuxef83GM2', 'dl.jpg', 1);
insert into UserProfile (Id, FirstName, LastName, Email, Phone, Bio, FirebaseId, ImageLocation, IsActive) values (3, 'Susanna', 'Tudgay', 'user2@test.com', '943-761-7253', 'I am the very model of a modern Major-General. I''ve information vegetable, animal, and mineral. I know the kings of England, and I quote the fights historical, from Marathon to Waterloo, in order categorical. I''m very well acquainted too with matters mathematical. I understand equations, both the simple and quadratical. About binomial theorem I''m teeming with a lot o'' news with many cheerful facts about the square of the hypotenuse', 'kHX8JeSEe3TdE6o0p9iT2iIHxD12', 'girl-guitar.png', 1);
insert into UserProfile (Id, FirstName, LastName, Email, Phone, Bio, FirebaseId, ImageLocation, IsActive) values (4, 'Dalton', 'Zute', 'user3@test.com', '690-165-2953', 'I am the very model of a modern Major-General. I''ve information vegetable, animal, and mineral. I know the kings of England, and I quote the fights historical, from Marathon to Waterloo, in order categorical. I''m very well acquainted too with matters mathematical. I understand equations, both the simple and quadratical. About binomial theorem I''m teeming with a lot o'' news with many cheerful facts about the square of the hypotenuse', 'fwijy4agn7mgyw238htz6urmujnm', 'live-singer.jpg', 1);
insert into UserProfile (Id, FirstName, LastName, Email, Phone, Bio, FirebaseId, ImageLocation, IsActive) values (5, 'Isidora', 'Latus', 'user4@test.com', '208-809-8433', 'I am the very model of a modern Major-General. I''ve information vegetable, animal, and mineral. I know the kings of England, and I quote the fights historical, from Marathon to Waterloo, in order categorical. I''m very well acquainted too with matters mathematical. I understand equations, both the simple and quadratical. About binomial theorem I''m teeming with a lot o'' news with many cheerful facts about the square of the hypotenuse', '4cvp789n1ez36w57pgvhpdcvmut4', 'piano-mixer.jpg', 1);
insert into UserProfile (Id, FirstName, LastName, Email, Phone, Bio, FirebaseId, ImageLocation, IsActive) values (6, 'Ddene', 'Maase', 'user6@test.com', '500-591-3263', 'I am the very model of a modern Major-General. I''ve information vegetable, animal, and mineral. I know the kings of England, and I quote the fights historical, from Marathon to Waterloo, in order categorical. I''m very well acquainted too with matters mathematical. I understand equations, both the simple and quadratical. About binomial theorem I''m teeming with a lot o'' news with many cheerful facts about the square of the hypotenuse', '93dpqx4fv6s0i9ianomj1bma9m0r', null, 1);
insert into UserProfile (Id, FirstName, LastName, Email, Phone, Bio, FirebaseId, ImageLocation, IsActive) values (7, 'Michell', 'MacCarter', 'user7@test.com', '962-664-4651', 'I am the very model of a modern Major-General. I''ve information vegetable, animal, and mineral. I know the kings of England, and I quote the fights historical, from Marathon to Waterloo, in order categorical. I''m very well acquainted too with matters mathematical. I understand equations, both the simple and quadratical. About binomial theorem I''m teeming with a lot o'' news with many cheerful facts about the square of the hypotenuse', 'ebgc7p3o9akpp9atvvex8nva5zvk', 'marchingdrum.jpg', 1);
insert into UserProfile (Id, FirstName, LastName, Email, Phone, Bio, FirebaseId, ImageLocation, IsActive) values (8, 'Malinde', 'Stammer', 'user8@test.com', '540-352-8490', 'I am the very model of a modern Major-General. I''ve information vegetable, animal, and mineral. I know the kings of England, and I quote the fights historical, from Marathon to Waterloo, in order categorical. I''m very well acquainted too with matters mathematical. I understand equations, both the simple and quadratical. About binomial theorem I''m teeming with a lot o'' news with many cheerful facts about the square of the hypotenuse', 't1deok0s3z40fllmw96vq85pplsg', null, 1);
insert into UserProfile (Id, FirstName, LastName, Email, Phone, Bio, FirebaseId, ImageLocation, IsActive) values (9, 'Sonya', 'O''Hone', 'user9@test.com', '662-490-3112', 'I am the very model of a modern Major-General. I''ve information vegetable, animal, and mineral. I know the kings of England, and I quote the fights historical, from Marathon to Waterloo, in order categorical. I''m very well acquainted too with matters mathematical. I understand equations, both the simple and quadratical. About binomial theorem I''m teeming with a lot o'' news with many cheerful facts about the square of the hypotenuse', 'p9v69klcuuprulya5278f1gbtqzv', 'stagedrum.jpg', 1);
insert into UserProfile (Id, FirstName, LastName, Email, Phone, Bio, FirebaseId, ImageLocation, IsActive) values (10, 'Holly', 'Bendley', 'user10@test.com', '869-649-4139', 'I am the very model of a modern Major-General. I''ve information vegetable, animal, and mineral. I know the kings of England, and I quote the fights historical, from Marathon to Waterloo, in order categorical. I''m very well acquainted too with matters mathematical. I understand equations, both the simple and quadratical. About binomial theorem I''m teeming with a lot o'' news with many cheerful facts about the square of the hypotenuse', 'xmz9hcbuq5oxmqhuezh43x3pfvcd', 'guitars.jpg', 1);
set identity_insert [UserProfile] off

set identity_insert [Location] on
insert into Location (Id, LocationName) values (1, 'Pantry');
insert into Location (Id, LocationName) values (2, 'Refrigerator');
insert into Location (Id, LocationName) values (3, 'Freezer');
set identity_insert [Location] off
